[app]
title = "Ingestador RAG (Powered by AnyDoc)"
categories = ["promociones", "técnico", "general"]

[chunking]
default_size = 800
default_overlap = 120
min_size = 200
max_size = 2000


[gemini]
model_name = "gemini-embedding-001"

[cohere]
model_name = "embed-multilingual-v3.0"

[huggingface]
# model_name = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
model_name = "sentence-transformers/all-MiniLM-L6-v2"

[vectorstore]
persist_dir = "./database/chroma_db"
collection_name = "anydoc_collection"