[app]
title = "Asistente RAG + Router"

[llm]
router_model = "gemini-2.5-flash-lite"
router_temperature = 0.0
router_thinking_budget = 0
rag_model = "gemini-2.5-flash"
rag_temperature = 0.0

[retrieval]
k_candidatos = 10
top_n = 4

[reranker]
default = "crossencoder"
crossencoder_model = "cross-encoder/ms-marco-MiniLM-L-6-v2"
cohere_model = "rerank-multilingual-v3.0"

[embeddings]
default_provider = "huggingface"

[gemini]
model_name = "gemini-embedding-001"

[cohere]
model_name = "embed-multilingual-v3.0"

[huggingface]
# model_name = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
model_name = "sentence-transformers/all-MiniLM-L6-v2"

[vectorstore]
persist_dir = "./database/chroma_db"
collection_name = "anydoc_collection"
