services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: ortelana_chroma
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSISTIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    
    volumes:
      - ./database/chroma_data:/chroma/chroma
    
    restart: unless-stopped

