services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: ortelana_chroma
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - ./database/chroma_data:/data
    restart: unless-stopped
    
  chroma-admin:
    image: fengzhichao/chromadb-admin
    container_name: ortelana_chroma_admin
    ports:
      - "3001:3001"
    environment:
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_HTTP_PORT=8000
    depends_on:
      - chromadb